# -*- coding: utf-8 -*-
"""RR.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j4Q_N_ffRfY8AfS0zaLnknh5Ye2-IuxI
"""

def round_robin(processes, time_quantum):
    n = len(processes)
    remaining_burst = [bt for _, bt in processes]
    waiting_times = [0] * n
    current_time = 0
    gantt_chart = []

    # Queue to keep track of process indexes
    from collections import deque
    queue = deque(range(n))

    # To track the last time each process was executed or arrived (for waiting time calculation)
    last_exec_time = [0] * n
    is_first_run = [True] * n

    while queue:
        i = queue.popleft()

        # If first time running, waiting time includes time from 0 to current_time
        if is_first_run[i]:
            waiting_times[i] = current_time
            is_first_run[i] = False
        else:
            # waiting time += time since last execution until now
            waiting_times[i] += current_time - last_exec_time[i]

        exec_time = min(time_quantum, remaining_burst[i])
        gantt_chart.append(f"{current_time} {processes[i][0]}")
        current_time += exec_time
        remaining_burst[i] -= exec_time
        last_exec_time[i] = current_time

        if remaining_burst[i] > 0:
            queue.append(i)

    gantt_chart.append(str(current_time))

    avg_waiting_time = sum(waiting_times) / n
    gantt_chart_str = " ".join(gantt_chart)

    return gantt_chart_str, avg_waiting_time


# Example usage:
processes = [('p1', 21), ('p2', 3), ('p3', 6), ('p4', 2)]
time_quantum = 5

gantt_chart, avg_wt = round_robin(processes, time_quantum)
print("Gantt Chart:", gantt_chart)
print(f"Average Waiting Time: {avg_wt:.2f}")